### ISSUE TITLE
썸네일이 박스 밖으로 나오는 문제

### ISSUE THREAD

**Issue by ch0213** [junghyeonsu/junghyeonsu.dev#4]
### Description
썸네일이 박스 밖으로 나옵니다

### Screenshot
<img width="486" alt="issue" src="https://user-images.githubusercontent.com/49121847/162063981-d0b0510f-511b-4d7f-a15d-1f5831ca59dd.png">

### 환경
macOs Monterey 12.1
MacBook Pro(16형, 2021년 모델)
크롬 버전 100.0.4896.60

**Comment by junghyeonsu** [comment]
@ch0213 감사합니다❤️

**Comment by junghyeonsu** [comment]
해결된 사진

<img width="477" alt="스크린샷 2022-04-07 오후 12 02 49" src="https://user-images.githubusercontent.com/54893898/162111924-f3ace7ae-0628-47ad-8d49-e761f6538829.png">
